version: "3.9"

services:
  maria:
    container_name: dbs_maria
    image: mariadb:latest
    restart: always
    healthcheck:
      test: "env | grep SHELL_SESSION_ID"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 15s
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - ./maria/conf.d:/etc/mysql/conf.d:ro
    networks:
      - upy-network

  mongo:
    container_name: dbs_mongo
    image: mongo:5.0.14
    restart: always
    healthcheck:
      test: "env | grep SHELL_SESSION_ID"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 15s
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - upy-network

  redis:
    container_name: dbs_redis
    image: redis:6.0-alpine
    restart: always
    ports:
      - 6379:6379
    env_file: .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD} --maxmemory-policy allkeys-lru --maxmemory 2G
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --no-auth-warning -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - upy-network

networks:
  upy-network:
    driver: bridge
    external: true